version: '3'

services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark

    networks:
      - mynet1

  spark-worker-1:
      image: bde2020/spark-worker:3.3.0-hadoop3.3
      container_name: spark-worker-1
      depends_on:
        - spark-master
      ports:
        - 8081:8081
      environment:
        - SPARK_MASTER=spark://spark-master:7077
      networks:
        - mynet1

  spark-worker-2:
      image: bde2020/spark-worker:3.3.0-hadoop3.3
      container_name: spark-worker-2
      depends_on:
        - spark-master
      ports:
        - 8082:8081
      environment:
        - SPARK_MASTER=spark://spark-master:7077
      networks:
        - mynet1

  sparkapp:
      image: sparkimage
      environment:
        - PRODUCTION=True
        - SOCKET_IP=0.0.0.0
        - SOCKET_PORT=9090
        - SPARKAPP_IP=sparkapp
      depends_on:
        - spark-master
      ports:
        - 5000:5000
      networks:
        - mynet1

      volumes:
        - ./sparkData:/data


networks:
  mynet:

  mynet1:

